version: "3.7"
services:
    app:
        container_name: hotelinking_web
        build:
            context: .
            dockerfile: .docker/Dockerfile
        ports:
            - "443:443"
            - "8080:80"
        volumes:
            - ./:/var/www/html
        depends_on:
            - db
    db:
        container_name: hotelinking_db
        image: mysql:5.7
        restart: always
        ports:
            - "3306:3306"
        command: --sql_mode=""
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - my-datavolume:/var/lib/mysql
volumes:
    my-datavolume:
